import { Metadata } from "next";
import styles from "./InfoBlock.module.scss";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const InfoBlock = ({ label }: { label: string }) => {
    return <div className={styles.container}>{label}</div>;
};
