import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navigation } from "@/components/Navigation/Navigation";
import styles from "./layout.module.scss";
import { Antonio, Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${styles.body} ${montserrat.className}`}>
                <div className={styles.header}>
                    <img
                        src={"/logo.png"}
                        alt="Logo"
                        className={styles.image}
                    />
                    <Navigation />
                </div>
                {children}
            </body>
        </html>
    );
}
